From 514d693441828bce3b596ee3f472418f4007e4fd Mon Sep 17 00:00:00 2001
From: Algent Albrahimi <algent@protonmail.com>
Date: Wed, 11 Aug 2021 22:51:27 +0200
Subject: [PATCH] Fix PyGIWarning "ensure that the right version gets loaded"

---
 gajim/gtk/emoji_data.py | 2 ++
 gajim/gtk/util.py       | 4 +++-
 2 files changed, 5 insertions(+), 1 deletion(-)

diff --git a/gajim/gtk/emoji_data.py b/gajim/gtk/emoji_data.py
index 5f1b62d..e36c54e 100644
--- a/gajim/gtk/emoji_data.py
+++ b/gajim/gtk/emoji_data.py
@@ -19,6 +19,8 @@ import weakref
 from enum import IntEnum
 from collections import OrderedDict
 
+import gi
+gi.require_version('GdkPixbuf', '2.0')
 from gi.repository import GdkPixbuf
 
 _MODIFIERS = ['\U0001F3FB',
diff --git a/gajim/gtk/util.py b/gajim/gtk/util.py
index fb6b39c..35e4cf2 100644
--- a/gajim/gtk/util.py
+++ b/gajim/gtk/util.py
@@ -35,7 +35,9 @@ try:
     from PIL import Image
 except Exception:
     pass
-
+import gi
+gi.require_version('Gtk', '3.0')
+gi.require_version('Gdk', '3.0')
 from gi.repository import Gdk
 from gi.repository import Gtk
 from gi.repository import GLib
-- 
2.32.0

